name: CI

on:
  push:
    branches:
    - hexo

env:
  GIT_USER: Sowevo
  GIT_EMAIL: i@sowevo.com


jobs:
  build:
      strategy:
        matrix:
          os: [ubuntu-latest]
          node_version: [12.x]
    runs-on: ${{ matrix.os }}


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
          submodules: true

    - name: Use Node.js lts
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}


    - name: prepare build env
      env:
        HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}

      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name $GIT_USER
        git config --global user.email $GIT_EMAIL
    - name: Install dependencies
      run: |
        npm i -g hexo-cli
        npm i

    - name: deploy to github 
      run: |
        hexo generate && hexo deploy
